For Regression Test

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
import statsmodels.api as sm

In [2]:
Airbnb_data = pd.read_csv('Airbnb_data_encoded_V3.csv')

In [3]:
Airbnb_data

,Price,Entire home/apt,Shared Room,Private Room,Person Capacity,Superhost,Multiple Rooms,Business,Cleanliness Rating,Guest Satisfaction,...,City_Athens,City_Barcelona,City_Berlin,City_Budapest,City_Lisbon,City_Paris,City_Rome,City_Vienna,Day_Weekday,Day_Weekend
0,194.033698,True,False,True,2.0,False,1,0,100.0,93.0,...,0,0,0,0,0,0,0,0,1,0
1,344.245776,True,False,True,4.0,False,0,0,75.0,85.0,...,0,0,0,0,0,0,0,0,1,0
2,264.101422,True,False,True,2.0,False,0,1,87.5,87.0,...,0,0,0,0,0,0,0,0,1,0
3,433.529398,True,False,True,4.0,False,0,1,87.5,90.0,...,0,0,0,0,0,0,0,0,1,0
4,485.552926,True,False,True,2.0,True,0,0,100.0,98.0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41709,715.938574,True,False,False,6.0,False,0,1,100.0,100.0,...,0,0,0,0,0,0,0,1,0,1
41710,304.793960,True,False,False,2.0,False,0,0,75.0,86.0,...,0,0,0,0,0,0,0,1,0,1
41711,637.168969,True,False,False,2.0,False,0,0,100.0,93.0,...,0,0,0,0,0,0,0,1,0,1
41712,301.054157,True,False,True,2.0,False,0,0,100.0,87.0,...,0,0,0,0,0,0,0,1,0,1
41713,133.230489,True,False,True,4.0,True,1,0,100.0,93.0,...,0,0,0,0,0,0,0,1,0,1

In [4]:
Airbnb_data.dtypes

Price                          float64
Entire home/apt                   bool
Shared Room                       bool
Private Room                      bool
Person Capacity                float64
Superhost                         bool
Multiple Rooms                   int64
Business                         int64
Cleanliness Rating             float64
Guest Satisfaction             float64
Bedrooms                       float64
City Center (km)               float64
Metro Distance (km)            float64
Attraction Index               float64
Normalised Attraction Index    float64
Restraunt Index                float64
Normalised Restraunt Index     float64
City_Amsterdam                   int64
City_Athens                      int64
City_Barcelona                   int64
City_Berlin                      int64
City_Budapest                    int64
City_Lisbon                      int64
City_Paris                       int64
City_Rome                        int64
City_Vienna                      int64
Day_Weekday                      int64
Day_Weekend                      int64
dtype: object

In [7]:
Airbnb_data = pd.get_dummies(Airbnb_data)

In [10]:
Airbnb_data

,Price,Entire home/apt,Shared Room,Private Room,Person Capacity,Superhost,Multiple Rooms,Business,Cleanliness Rating,Guest Satisfaction,...,City_Athens,City_Barcelona,City_Berlin,City_Budapest,City_Lisbon,City_Paris,City_Rome,City_Vienna,Day_Weekday,Day_Weekend
0,194.033698,True,False,True,2.0,False,1,0,100.0,93.0,...,0,0,0,0,0,0,0,0,1,0
1,344.245776,True,False,True,4.0,False,0,0,75.0,85.0,...,0,0,0,0,0,0,0,0,1,0
2,264.101422,True,False,True,2.0,False,0,1,87.5,87.0,...,0,0,0,0,0,0,0,0,1,0
3,433.529398,True,False,True,4.0,False,0,1,87.5,90.0,...,0,0,0,0,0,0,0,0,1,0
4,485.552926,True,False,True,2.0,True,0,0,100.0,98.0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41709,715.938574,True,False,False,6.0,False,0,1,100.0,100.0,...,0,0,0,0,0,0,0,1,0,1
41710,304.793960,True,False,False,2.0,False,0,0,75.0,86.0,...,0,0,0,0,0,0,0,1,0,1
41711,637.168969,True,False,False,2.0,False,0,0,100.0,93.0,...,0,0,0,0,0,0,0,1,0,1
41712,301.054157,True,False,True,2.0,False,0,0,100.0,87.0,...,0,0,0,0,0,0,0,1,0,1
41713,133.230489,True,False,True,4.0,True,1,0,100.0,93.0,...,0,0,0,0,0,0,0,1,0,1

In [11]:
Airbnb_data.dtypes

Price                          float64
Entire home/apt                   bool
Shared Room                       bool
Private Room                      bool
Person Capacity                float64
Superhost                         bool
Multiple Rooms                   int64
Business                         int64
Cleanliness Rating             float64
Guest Satisfaction             float64
Bedrooms                       float64
City Center (km)               float64
Metro Distance (km)            float64
Attraction Index               float64
Normalised Attraction Index    float64
Restraunt Index                float64
Normalised Restraunt Index     float64
City_Amsterdam                   int64
City_Athens                      int64
City_Barcelona                   int64
City_Berlin                      int64
City_Budapest                    int64
City_Lisbon                      int64
City_Paris                       int64
City_Rome                        int64
City_Vienna                      int64
Day_Weekday                      int64
Day_Weekend                      int64
dtype: object

In [13]:
y = Airbnb_data['Price']

# Set the other columns as the independent variables, excluding 'City' and 'Room type'
X = Airbnb_data[['Entire home/apt',
                 'Shared Room',                     
                 'Private Room',                     
                 'Person Capacity',               
                 'Superhost',                         
                 'Multiple Rooms',                  
                 'Business',                         
                 'Cleanliness Rating',            
                 'Guest Satisfaction',            
                 'Bedrooms',                       
                 'City Center (km)',              
                 'Metro Distance (km)',            
                 'Attraction Index',               
                 'Normalised Attraction Index',    
                 'Restraunt Index',                
                 'Normalised Restraunt Index',     
                 'City_Amsterdam',                  
                 'City_Athens',                     
                 'City_Barcelona',                  
                 'City_Berlin',                     
                 'City_Budapest',                    
                 'City_Lisbon',                     
                 'City_Paris',                      
                 'City_Rome',                        
                 'City_Vienna',                      
                 'Day_Weekday',
                 'Day_Weekend']]

X[['Entire home/apt', 'Shared Room', 'Private Room', 'Superhost']] = X[['Entire home/apt', 'Shared Room', 'Private Room', 'Superhost']].astype(int)

# Add a column of 1's to include an intercept in the model
X = sm.add_constant(X)

# Instantiate and fit the model
model = sm.OLS(y, X)
results = model.fit()

# Print the model summary
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Price   R-squared:                       0.260
Model:                            OLS   Adj. R-squared:                  0.260
Method:                 Least Squares   F-statistic:                     611.2
Date:                Thu, 13 Jul 2023   Prob (F-statistic):               0.00
Time:                        10:22:06   Log-Likelihood:            -2.8786e+05
No. Observations:               41714   AIC:                         5.758e+05
Df Residuals:                   41689   BIC:                         5.760e+05
Df Model:                          24
Covariance Type:            nonrobust
===============================================================================================
                                  coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
Entire home/apt               -28.0361      9.741     -2.878      0.004     -47.129      -8.943
Shared Room                  -192.1430     13.748    -13.976      0.000    -219.089    -165.197
Private Room                  -86.1138      3.228    -26.677      0.000     -92.441     -79.787
Person Capacity                21.7643      1.278     17.033      0.000      19.260      24.269
Superhost                      -1.6264      2.813     -0.578      0.563      -7.141       3.888
Multiple Rooms                 11.8817      3.034      3.916      0.000       5.935      17.828
Business                       40.1648      3.080     13.039      0.000      34.127      46.202
Cleanliness Rating              0.4696      0.149      3.157      0.002       0.178       0.761
Guest Satisfaction              0.7409      0.207      3.575      0.000       0.335       1.147
Bedrooms                        7.1052      0.231     30.743      0.000       6.652       7.558
City Center (km)                0.3332      0.941      0.354      0.723      -1.511       2.177
Metro Distance (km)             0.8045      2.076      0.388      0.698      -3.264       4.873
Attraction Index               -0.0486      0.019     -2.616      0.009      -0.085      -0.012
Normalised Attraction Index     5.6468      0.467     12.102      0.000       4.732       6.561
Restraunt Index                -0.0049      0.008     -0.634      0.526      -0.020       0.010
Normalised Restraunt Index      0.8872      0.181      4.895      0.000       0.532       1.242
City_Amsterdam                291.3692      5.379     54.166      0.000     280.826     301.913
City_Athens                  -136.8535      4.192    -32.645      0.000    -145.070    -128.637
City_Barcelona                 53.6817      5.408      9.927      0.000      43.083      64.281
City_Berlin                   -33.0317      6.899     -4.788      0.000     -46.555     -19.509
City_Budapest                -149.1238      4.371    -34.117      0.000    -157.691    -140.557
City_Lisbon                   -44.4023      3.925    -11.312      0.000     -52.096     -36.708
City_Paris                     80.6592      4.012     20.106      0.000      72.796      88.522
City_Rome                     -64.6669      4.792    -13.496      0.000     -74.058     -55.275
City_Vienna                   -25.6679      4.588     -5.595      0.000     -34.660     -16.675
Day_Weekday                   -17.9140      5.021     -3.568      0.000     -27.756      -8.072
Day_Weekend                   -10.1221      5.006     -2.022      0.043     -19.934      -0.310
==============================================================================
Omnibus:                   116159.888   Durbin-Watson:                   1.866
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       7694417492.001
Skew:                          35.828   Prob(JB):                         0.00
Kurtosis:                    2105.813   Cond. No.                     1.27e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.07e-22. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

C:\Users\31332\AppData\Local\Temp\ipykernel_25604\2137236804.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[['Entire home/apt', 'Shared Room', 'Private Room', 'Superhost']] = X[['Entire home/apt', 'Shared Room', 'Private Room', 'Superhost']].astype(int)